[workspace]

members = ["creator", "run-wasm", "shared", "clients/client"]
resolver = "2"

[workspace.dependencies]
theframework = { version = "0.1.40", git = "https://github.com/markusmoenig/TheFramework", features = [
    "ui",
], default-features = true }
# theframework = { path = "../TheFramework", features = [
#     "ui",
# ], default-features = true }

rusterix = { version = "0.2.8", git = "https://github.com/markusmoenig/Rusterix" }
codegridfx = { git = "https://github.com/markusmoenig/Rusterix", package = "codegridfx" }
rusteria = { git = "https://github.com/markusmoenig/Rusterix", package = "rusteria" }
scenevm = { version = "0.1", git = "https://github.com/markusmoenig/SceneVM" }

# rusterix = { path = "../Rusterix" }
# codegridfx = { path = "../Rusterix/codegridfx/lib", package = "codegridfx" }
# rusteria = { path = "../Rusterix/rusteria", package = "rusteria" }
# scenevm = { path = "../SceneVM" }

[workspace.package]
edition = "2024"
version = "0.8.90"
license = "MIT"
authors = ["Markus Moenig"]
description = "A game creator for classical RPGs."
