[package]
name = "rusteria"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Rusteria is a fast shader-like programming language."
keywords = ["shader", "rendering", "graphics", "procedural", "texture"]
readme = "README.md"

[dependencies]
theframework.workspace = true

rustc-hash = "2.1.1"
indexmap = "2.10.0"
rayon = "1.11.0"
vek = { version = "0.17.1", default-features = true }
image = { version = "0.25", features = ["png"] }
once_cell = "1.21.3"
rust-embed = { version = "8", default-features = true, features = [
    "include-exclude",
] }
strum = { version = "0.27", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ['Window'] }
